

class MetaFunctionError(Exception):
    pass

class ConcurrentException(MetaFunctionError):
    pass
